name = "booster-app"
type = 'webpack'
account_id = ''
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
compatibility_date = "2021-11-18"

[build]
command = "yarn && yarn run build"

[build.upload]
format = "service-worker"
